Repository firebase/firebase-tools, pull requests merged in 2019-06, with the labels that each got.

#1356 Add `force: true` when using firebase-tools as module
  README.md
Labels: cla: yes

#1354 Fix deletes for numeric IDs
  changelog.txt
  src/firestore/delete.js
Labels: cla: yes

#1362 FIX: hostname value on emulated rewrited function
  changelog.txt
  src/emulator/functionsEmulatorRuntime.ts
  src/test/emulators/functionsEmulatorRuntime.spec.ts
Labels: cla: yes

#1368 Changelog for #1224
  changelog.txt
Labels: cla: yes

#1369 Release database emulator v4.0.0
  changelog.txt
  src/serve/javaEmulators.ts
Labels: cla: yes

#1338 Update `inquirer`, ts-ify `prompt`
  package.json
  src/RulesDeploy.ts
  src/auth.js
  src/commands/database-remove.js
  src/commands/database-set.js
  src/commands/database-update.js
  src/commands/firestore-delete.js
  src/commands/functions-delete.js
  src/commands/hosting-disable.js
  src/commands/init.js
  src/commands/login.js
  src/commands/open.js
  src/commands/tools-migrate.js
  src/commands/use.js
  src/config.js
  src/deploy/functions/release.js
  src/init/features/database.js
  src/init/features/firestore.ts
  src/init/features/functions/index.js
  src/init/features/functions/javascript.js
  src/init/features/functions/npm-dependencies.js
  src/init/features/functions/typescript.js
  src/init/features/hosting.js
  src/init/features/project.js
  src/init/features/storage.js
  src/init/index.js
  src/prompt.js
  src/prompt.ts
  src/test/prompt.spec.ts
Labels: cla: yes

#1220 [Breaking Change] Enforce engines field present in package.json for functions deploys
  changelog.txt
  src/deploy/functions/validate.ts
  src/test/deploy/functions/validate.spec.ts
Labels: cla: yes, ready

#1376 Support FIRESTORE_EMULATOR_HOST variable
  changelog.txt
  src/commands/emulators-exec.ts
  src/emulator/firestoreEmulator.ts
Labels: cla: yes

#1377 Functions Log: add better handling for unknown values
  changelog.txt
  src/commands/functions-log.ts
Labels: cla: yes

#1374 Remove no-use-before-declare from tslint.json
  templates/init/functions/typescript/tslint.json
Labels: cla: yes

#1366 Fixes #1320, #1322, #1364, and #1312
  changelog.txt
  package.json
  src/RulesDeploy.ts
  src/auth.js
  src/commands/database-remove.js
  src/commands/database-set.js
  src/commands/database-update.js
  src/commands/emulators-exec.ts
  src/commands/firestore-delete.js
  src/commands/functions-delete.js
  src/commands/functions-log.ts
  src/commands/hosting-disable.js
  src/commands/init.js
  src/commands/login.js
  src/commands/open.js
  src/commands/tools-migrate.js
  src/commands/use.js
  src/config.js
  src/deploy/functions/release.js
  src/emulator/firestoreEmulator.ts
  src/emulator/functionsEmulator.ts
  src/emulator/functionsEmulatorRuntime.ts
  src/emulator/functionsEmulatorShared.ts
  src/emulator/functionsEmulatorUtils.ts
  src/init/features/database.js
  src/init/features/firestore.ts
  src/init/features/functions/index.js
  src/init/features/functions/javascript.js
  src/init/features/functions/npm-dependencies.js
  src/init/features/functions/typescript.js
  src/init/features/hosting.js
  src/init/features/project.js
  src/init/features/storage.js
  src/init/index.js
  src/prompt.js
  src/prompt.ts
  src/test/emulators/functionsEmulator.spec.ts
  src/test/emulators/functionsEmulatorRuntime.spec.ts
  src/test/emulators/functionsEmulatorUtils.spec.ts
  src/test/prompt.spec.ts
Labels: cla: yes

#1379 Ensure we raise error when function code errors on load
  src/emulator/functionsEmulator.ts
  src/emulator/functionsEmulatorRuntime.ts
Labels: cla: yes

#1380 Release Firestore emulator v1.5.0
  changelog.txt
  src/serve/javaEmulators.ts
Labels: cla: yes

#1370 Typescriptify project init flow
  src/firebaseApi.js
  src/firebaseApi.ts
  src/init/features/index.js
  src/init/features/project.js
  src/init/features/project.ts
  src/init/features/storage.ts
Labels: cla: yes

#1375 Update init templates to use latest Functions and Admin SDKs
  changelog.txt
  templates/init/functions/javascript/package.lint.json
  templates/init/functions/javascript/package.nolint.json
  templates/init/functions/typescript/package.lint.json
  templates/init/functions/typescript/package.nolint.json
Labels: cla: yes

#1381 Add tests to project, storage, and firestore init flows
  src/init/features/firestore.ts
  src/init/features/firestore/index.ts
  src/init/features/firestore/indexes.ts
  src/init/features/firestore/rules.ts
  src/init/features/functions/index.js
  src/init/features/project.ts
  src/init/features/storage.ts
  src/requireAccess.ts
  src/test/init/features/firestore.spec.ts
  src/test/init/features/project.spec.ts
  src/test/init/features/storage.spec.ts
Labels: cla: yes

#1387 Make emulators:exec exit with non-zero code when script fails
  changelog.txt
  src/commands/emulators-exec.ts
Labels: cla: no

#1386 made body-parser size limits 10mb per https://cloud.google.com/functi…
  changelog.txt
  src/emulator/functionsEmulatorRuntime.ts
Labels: cla: yes

#1383 Adds check for cloud resource location for features that require it
  changelog.txt
  src/ensureCloudResourceLocation.ts
  src/gcp/cloudscheduler.ts
  src/init/features/firestore/index.ts
  src/init/features/project.ts
  src/init/features/storage.ts
  src/test/gcp/cloudscheduler.spec.ts
  src/test/init/features/firestore.spec.ts
  src/test/init/features/project.spec.ts
  src/test/init/features/storage.spec.ts
Labels: cla: yes

#1390 Fix bug where location not set when .firebaserc exists
  src/init/features/project.ts
  src/test/init/features/project.spec.ts
Labels: cla: yes

#1391 Remove outdated warning about functions delay
  src/deploy/index.js
Labels: cla: yes

#1393 Update `firebase-admin` in `next`
  package.json
Labels: cla: yes

#1392 Breaking Updates (v7!)
  .travis.yml
  changelog.txt
  package.json
  src/bin/firebase.js
  src/deploy/functions/validate.ts
  src/emulator/constants.ts
  src/emulator/controller.ts
  src/emulator/databaseEmulator.ts
  src/emulator/functionsEmulator.ts
  src/emulator/functionsEmulatorRuntime.ts
  src/emulator/functionsEmulatorShared.ts
  src/emulator/functionsEmulatorUtils.ts
  src/serve/javaEmulators.ts
  src/test/deploy/functions/validate.spec.ts
  src/test/emulators/functionsEmulator.spec.ts
  src/test/emulators/functionsEmulatorRuntime.spec.ts
  src/test/emulators/functionsEmulatorUtils.spec.ts
  templates/init/functions/javascript/package.lint.json
  templates/init/functions/javascript/package.nolint.json
  templates/init/functions/typescript/package.lint.json
  templates/init/functions/typescript/package.nolint.json
Labels: cla: yes

#1344 Add package-lock.json.
  .github/CONTRIBUTING.md
  .gitignore
  package-lock.json
Labels: cla: yes

#1396 remove es6-set
  package-lock.json
  package.json
  src/profileReport.js
Labels: cla: yes

#1397 Move `firebase` dependency
  package-lock.json
  package.json
Labels: cla: yes

#1399 Make functions serve respect the host argument
  changelog.txt
  src/emulator/functionsEmulator.ts
  src/emulator/functionsEmulatorShell.ts
  src/hosting/functionsProxy.ts
  src/serve/functions.ts
Labels: cla: yes

#1401 swap opn (deprecated) for open
  package-lock.json
  package.json
  src/auth.js
  src/commands/functions-log.ts
  src/commands/open.js
Labels: cla: yes

#1410 Use ChannelCredentials instead of ServerCredentials
  changelog.txt
  package-lock.json
  src/emulator/functionsEmulatorRuntime.ts
Labels: cla: yes

#1413 register rtdb triggers per-namespace in functions emulator
  src/emulator/constants.ts
  src/emulator/functionsEmulator.ts
Labels: cla: yes

#1403 rewrite `open` command to typescript
  changelog.txt
  src/commands/open.js
  src/commands/open.ts
Labels: cla: yes

#1402 remove `is`, rewrite encodeFirestoreObject
  package-lock.json
  package.json
  src/firestore/encodeFirestoreValue.js
  src/firestore/encodeFirestoreValue.ts
  src/localFunction.js
  src/test/firestore/encodeFirestoreValue.ts
Labels: cla: yes

#1423 set inquirer to only update patch version
  changelog.txt
  package-lock.json
  package.json
Labels: cla: yes

#1378 Update Throttler to support task master timeout
  src/test/throttler/throttler.spec.ts
  src/throttler/errors/retries-exhausted-error.ts
  src/throttler/errors/task-error.ts
  src/throttler/errors/timeout-error.ts
  src/throttler/throttler.ts
Labels: cla: yes

#1411 Fully support RTDB functions and use firebase-functions 3.x
  changelog.txt
  package-lock.json
  package.json
  src/emulator/events/types.ts
  src/emulator/functionsEmulator.ts
  src/emulator/functionsEmulatorRuntime.ts
  src/emulator/functionsEmulatorShared.ts
Labels: cla: yes

#1425 add end-to-end test for emulator function triggers
  .travis.yml
  scripts/test-triggers-end-to-end.sh
  scripts/triggers-end-to-end-tests/.firebaserc
  scripts/triggers-end-to-end-tests/.gitignore
  scripts/triggers-end-to-end-tests/README.md
  scripts/triggers-end-to-end-tests/firebase.json
  scripts/triggers-end-to-end-tests/functions/.gitignore
  scripts/triggers-end-to-end-tests/functions/index.js
  scripts/triggers-end-to-end-tests/functions/package.json
  scripts/triggers-end-to-end-tests/package.json
  scripts/triggers-end-to-end-tests/run.spec.js
Labels: cla: yes

#1424 Fix issue 1346
  changelog.txt
  src/emulator/functionsEmulatorRuntime.ts
Labels: cla: yes

#1400 Implement LRO polling utility
  src/operation-poller.ts
  src/test/operation-poller.spec.ts
Labels: cla: yes

#1434 Auto-download emulators through emulators:start
  changelog.txt
  package-lock.json
  package.json
  src/emulator/controller.ts
  src/emulator/databaseEmulator.ts
  src/emulator/download.ts
  src/emulator/firestoreEmulator.ts
  src/emulator/types.ts
  src/serve/javaEmulators.ts
Labels: cla: yes

#1428 Make functions:shell respect the port argument
  changelog.txt
  src/serve/functions.ts
Labels: cla: yes

#1433 Fix error message for port conflict
  changelog.txt
  package-lock.json
  src/emulator/controller.ts
  src/emulator/emulatorServer.ts
  src/emulator/registry.ts
Labels: cla: yes

#1437 Allow some emulators to start without config
  changelog.txt
  src/commands/emulators-exec.ts
  src/commands/emulators-start.ts
  src/emulator/commandUtils.ts
  src/emulator/controller.ts
Labels: cla: yes

#1446 Firestore Emulator v1.6.0
  changelog.txt
  src/serve/javaEmulators.ts
Labels: cla: yes
