Repository firebase/firebase-tools, pull requests merged in 2019-05, with the labels that each got.

#1218 Refactor deploy/functions/prepare logic and add tests
  src/config.js
  src/deploy/functions/prepare.js
  src/deploy/functions/validate.ts
  src/deploy/hosting/prepare.js
  src/projectPath.ts
  src/resolveProjectPath.js
  src/test/deploy/functions/validate.spec.ts
Labels: cla: yes, ready

#1234 Deprecate user-home in favor of os.homedir()
  package.json
  src/commands/init.js
  src/emulator/constants.js
Labels: cla: yes

#1223 Add Node 10 runtime, add deprecation warning when deploying with Node 6, keep default to Node 6 but add warnings
  changelog.txt
  package.json
  src/deploy/functions/release.js
  src/functionsDeployHelper.js
  src/prepareFunctionsUpload.js
  src/runtimeChoiceSelector.ts
  src/test/helpers/mocha-bootstrap.js
  src/test/runtimeChoiceSelector.spec.ts
Labels: cla: yes, ready

#1173 Add engines to package.json during firebase init functions
  templates/init/functions/javascript/eslint.json
  templates/init/functions/javascript/package.lint.json
  templates/init/functions/javascript/package.nolint.json
  templates/init/functions/typescript/package.lint.json
  templates/init/functions/typescript/package.nolint.json
  templates/init/functions/typescript/tsconfig.json
Labels: cla: yes, ready

#1238 Fix package.json from bad merge
  package.json
Labels: cla: yes

#1240 Functions Emulator Patches
  changelog.txt
  src/commands/serve.js
  src/emulator/controller.ts
  src/emulator/functionsEmulator.ts
  src/emulator/functionsEmulatorRuntime.ts
  src/test/emulators/functionsEmulatorRuntime.spec.ts
Labels: cla: yes

#1241 Fix use of undefined 'name' variable
  .eslintrc
  changelog.txt
  package.json
  src/emulator/functionsEmulator.ts
  tslint.json
Labels: cla: yes

#1244 Fix bugs with serve vs emulators:start
  changelog.txt
  src/commands/serve.js
  src/emulator/emulatorServer.ts
  src/functionsShellCommandAction.js
  src/serve/functions.ts
  src/serve/hosting.js
  src/serve/index.js
  templates/init/functions/javascript/package.lint.json
  templates/init/functions/javascript/package.nolint.json
Labels: cla: yes

#1248 Make sure emulator success log message always shows
  changelog.txt
  src/emulator/emulatorServer.ts
  src/emulator/registry.ts
Labels: cla: yes

#1247 Revert changes to default RTDB + Firestore emulator ports
  changelog.txt
  src/emulator/constants.ts
Labels: cla: yes

#1250 Disable functions emulator advanced features when 'served'
  changelog.txt
  src/emulator/functionsEmulator.ts
  src/emulator/functionsEmulatorRuntime.ts
  src/serve/functions.ts
Labels: cla: yes

#1249 Fixes emulator rules and google-gax resolution
  changelog.txt
  src/emulator/controller.ts
  src/emulator/functionsEmulator.ts
  src/emulator/functionsEmulatorRuntime.ts
  src/emulator/functionsEmulatorShared.ts
  src/test/emulators/functionsEmulatorRuntime.spec.ts
Labels: cla: yes

#1251 Fixes incorrect "Cloud Firestore emulator is not running" error
  changelog.txt
  src/emulator/functionsEmulatorRuntime.ts
Labels: cla: yes

#1252 Adds `protect_env` and `admin_stubs` to disable-able emulator features
  src/emulator/functionsEmulator.ts
  src/emulator/functionsEmulatorRuntime.ts
  src/emulator/functionsEmulatorShared.ts
  src/serve/functions.ts
Labels: cla: yes

#1226 RTDB profiler could expose queueing delay
  changelog.txt
  src/profileReport.js
  src/test/fixtures/profiler-data/sample-output.json
  src/test/fixtures/profiler-data/sample.json
Labels: cla: yes

#1263 Emulator Runtime Patches
  changelog.txt
  src/emulator/functionsEmulator.ts
  src/emulator/functionsEmulatorRuntime.ts
  src/emulator/functionsEmulatorShared.ts
  src/emulator/types.ts
  src/test/emulators/functionsEmulatorRuntime.spec.ts
Labels: DO NOT MERGE, cla: yes

#1267 Make serve functions respect the --port flag
  src/emulator/functionsEmulator.ts
  src/serve/functions.ts
Labels: cla: yes

#1268 Changelog for #1267
  changelog.txt
Labels: cla: yes

#1269 Fixes this.options vs options in serve
  src/emulator/functionsEmulatorRuntime.ts
  src/serve/functions.ts
Labels: cla: yes

#1284 Dont watch node_modules folder
  changelog.txt
  src/emulator/functionsEmulator.ts
Labels: cla: yes

#1286 Properly set CORS headers for emulated functions
  changelog.txt
  src/emulator/functionsEmulator.ts
Labels: cla: yes

#1287 Emulator fixes for #1281, #1279, and #1277
  package.json
  src/emulator/functionsEmulator.ts
  src/emulator/functionsEmulatorRuntime.ts
  src/emulator/functionsEmulatorUtils.ts
  src/test/emulators/fixtures.ts
  src/test/emulators/functionsEmulator.spec.ts
  src/test/emulators/functionsEmulatorRuntime.spec.ts
Labels: cla: yes

#1291 Changelog for #1287
  changelog.txt
Labels: cla: yes

#1225 Add commands to create and list RTDB instances
  changelog.txt
  src/commands/database-instances-create.ts
  src/commands/database-instances-list.ts
  src/commands/index.js
  src/gcp/firedata.ts
Labels: cla: yes

#1294 Wait for download pipeline to flush before resolving
  changelog.txt
  src/emulator/download.ts
Labels: cla: yes

#1298 Actually write emulator debug logs to the file.
  src/serve/javaEmulators.ts
Labels: cla: yes

#1260 Integrate functions:shell with the new emulator
  changelog.txt
  package.json
  src/emulator/constants.ts
  src/emulator/emulatorLogger.ts
  src/emulator/events/types.ts
  src/emulator/functionsEmulator.ts
  src/emulator/functionsEmulatorRuntime.ts
  src/emulator/functionsEmulatorShared.ts
  src/emulator/functionsEmulatorShell.ts
  src/functionsShellCommandAction.js
  src/serve/functions.ts
  src/test/emulators/fixtures.ts
  src/test/emulators/functionsEmulatorRuntime.spec.ts
Labels: cla: yes

#1307 Firestore emulator warns when rules file not found
  changelog.txt
  src/emulator/controller.ts
  src/emulator/firestoreEmulator.ts
Labels: cla: yes

#1306 Fixes #1280 - Emulator Socket on Windows
  changelog.txt
  src/emulator/functionsEmulatorRuntime.ts
  src/emulator/functionsEmulatorShared.ts
  src/test/emulators/functionsEmulatorRuntime.spec.ts
Labels: cla: yes

#1311 Automatic emulator firebase-admin initialization, fixes #1278
  changelog.txt
  src/emulator/functionsEmulator.ts
  src/emulator/functionsEmulatorRuntime.ts
  src/test/emulators/functionsEmulatorRuntime.spec.ts
Labels: cla: yes

#1313 update changelog format for new publish notes
  changelog.txt
Labels: cla: yes

#1318 Release Cloud Firestore emulator v1.4.6
  changelog.txt
  src/serve/javaEmulators.ts
Labels: cla: yes

#1321 Amend changelog with more details about Firestore Emulator v1.4.6
  changelog.txt
Labels: cla: yes

#1330 TypeScript-ify firestore API
  src/gcp/firestore.ts
Labels: cla: yes

#1331 Recursively split Firestore delete batches if we encounter errors
  src/gcp/firestore.ts
Labels: cla: yes

#1332 Fix HTTP routing issues
  changelog.txt
  src/emulator/functionsEmulator.ts
  src/emulator/functionsEmulatorRuntime.ts
  src/emulator/functionsEmulatorUtils.ts
  src/test/emulators/functionsEmulatorUtils.spec.ts
Labels: cla: yes

#1224 No longer recreating unchanged schedules
  src/gcp/cloudscheduler.ts
  src/test/gcp/cloudscheduler.spec.ts
Labels: cla: yes

#1335 Allow runtime function to handle CORS
  changelog.txt
  src/emulator/functionsEmulator.ts
Labels: cla: yes

#1340 Inherit env and disable noop piping for emulators:exec.
  changelog.txt
  src/commands/emulators-exec.ts
Labels: cla: yes

#1297 Refactor `listPath` API for size node API in #1272
  src/database/listRemote.ts
  src/database/remove.ts
  src/database/removeRemote.ts
  src/test/database/fakeListRemote.spec.ts
  src/test/database/fakeRemoveRemote.spec.ts
  src/test/database/listRemote.spec.ts
  src/test/database/remove.spec.ts
  src/test/database/removeRemote.spec.ts
Labels: cla: yes

#1349 Print error and exit early with Node 6
  .travis.yml
  changelog.txt
  package.json
  src/bin/firebase.js
Labels: cla: yes

#1348 Modify use command to call new Public API when fetching projects
  changelog.txt
  src/commands/use.js
Labels: cla: yes

#1336 Escapes commas in displayName when exporting users in CSV format.
  changelog.txt
  src/accountExporter.js
  src/test/accountExporter.spec.js
Labels: cla: yes

#1355 Remove prepublish script (and typo)
  changelog.txt
  package.json
Labels: cla: yes
