Repository firebase/firebase-tools, pull requests merged in 2019-01, with the labels that each got.

#1082 Firestore indexes bug fixes
  src/firestore/indexes-api.ts
  src/firestore/indexes.ts
  src/test/firestore/indexes.spec.ts
Labels: cla: yes

#1068 Transition to cross-env-shell for lifecyle hooks
  src/deploy/lifecycleHooks.js
Labels: cla: yes

#1083 Release Firestore Emulator v1.2.3
  changelog.txt
  src/emulator/constants.js
Labels: cla: yes

#1085 Update changelog.txt for #1082
  changelog.txt
Labels: cla: yes

#1079 Added isGlobal to update notifier.
  src/bin/firebase.js
Labels: cla: yes

#1092 Adds messaging that functions may take up to 30s to propagate
  src/deploy/index.js
  src/serve/javaEmulators.js
Labels: cla: yes

#1086 Adding functions/.gitignore when javascript is chosen in firebase init, updating typescript functions/.gitignore
  changelog.txt
  src/init/features/functions/javascript.js
  templates/init/functions/javascript/_gitignore
  templates/init/functions/typescript/_gitignore
Labels: cla: yes

#1090 Prevent Functional Tests from running on a PR from a fork
  .travis.yml
Labels: cla: yes

#1047 make environment variables available to the deploy process
  src/parseTriggers.js
Labels: cla: yes, functions

#1096 Fix for 1095
  src/api.js
Labels: cla: yes

#1097 Verify downloads before installing emulators
  src/emulator/download.js
Labels: cla: yes

#1104 Firestore Emulator Release v1.3.0
  changelog.txt
  src/emulator/constants.js
Labels: cla: yes

#1107 functions `--open` fixes, plus typescript
  changelog.txt
  package.json
  src/commands/functions-log.js
  src/commands/functions-log.ts
Labels: cla: yes

#1093 Update Functions init templates
  changelog.txt
  templates/init/functions/javascript/package.lint.json
  templates/init/functions/typescript/package.lint.json
  templates/init/functions/typescript/package.nolint.json
  templates/init/functions/typescript/tsconfig.json
  templates/init/functions/typescript/tslint.json
Labels: cla: yes, cleanup, functions

#1094 Update issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: cla: yes

#1120 Prevent contention when creating Firestore indexes
  src/firestore/indexes.ts
Labels: cla: yes

#1122 Turn on template validation in OSS Bot
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: cla: yes

#1124 Adds optional FirepitVersion to UA Visitor definition
  src/track.js
Labels: cla: yes

#1114 Multipath large delete using writeSizeLimit=tiny
  src/commands/database-remove.js
  src/database/remove.ts
  src/database/removeRemote.ts
  src/test/database/fakeRemoveRemote.spec.ts
  src/test/database/remove.spec.ts
  src/test/database/removeRemote.spec.ts
Labels: cla: yes

#1129 add changelog entry for index contention
  changelog.txt
Labels: cla: yes

#1128 Updating package.jsons for functions 2.2.0
  changelog.txt
  templates/init/functions/javascript/package.lint.json
  templates/init/functions/javascript/package.nolint.json
  templates/init/functions/typescript/package.lint.json
  templates/init/functions/typescript/package.nolint.json
Labels: cla: yes
